apiVersion: v1
kind: BuildConfig
metadata:
  name: hits-server
  namespace: edspace
spec:
  output:
    to:
      kind: ImageStreamTag
      name: hits-server:latest
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/inorton/EDMCHitsServer.git
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers: []
status:
  lastVersion: 3
